import { useState } from 'react'
import CodeEditor from '../components/CodeEditor'
import Terminal from '../components/Terminal'

const sections = [
  { id: 'background',   title: '9.1 Background',            icon: '📖' },
  { id: 'binding',      title: '9.2 Address Binding',       icon: '🔗' },
  { id: 'contiguous',   title: '9.3 Contiguous Allocation', icon: '📦' },
  { id: 'paging',       title: '9.4 Paging',                icon: '📄' },
  { id: 'tlb',          title: '9.5 TLB & Performance',     icon: '⚡' },
  { id: 'structure',    title: '9.6 Page Table Structure',  icon: '🏗️' },
  { id: 'segmentation', title: '9.7 Segmentation',          icon: '✂️' },
  { id: 'simulator',    title: '🎮 Simulators',             icon: '🎮' },
  { id: 'lab',          title: '💻 Lab',                    icon: '💻' },
  { id: 'quiz',         title: '🧠 Quiz',                   icon: '🧠' },
]

const QUIZ = [
  {
    q: 'What is the difference between a logical address and a physical address?',
    options: [
      'They are the same thing',
      'Logical address is generated by the CPU; physical address is the actual location in memory hardware',
      'Physical address is used by the compiler; logical address by the CPU',
      'Logical addresses are only used in virtual memory'
    ],
    answer: 1,
    explanation: 'The CPU generates logical (virtual) addresses. The Memory Management Unit (MMU) translates these to physical addresses — actual locations in RAM. The program only sees logical addresses; the hardware handles the translation transparently.'
  },
  {
    q: 'What is internal fragmentation?',
    options: [
      'Unused memory between allocated partitions',
      'Wasted memory inside an allocated partition because the allocated block is larger than requested',
      'Memory that cannot be accessed',
      'Fragmentation caused by paging'
    ],
    answer: 1,
    explanation: 'Internal fragmentation is wasted space INSIDE an allocated partition. If a process needs 18KB and gets a 20KB partition, 2KB is wasted internally. Paging has internal fragmentation (last page may not be full). Fixed partitions have internal fragmentation.'
  },
  {
    q: 'In paging, if a page size is 4KB and a logical address is 13 bits, how many pages can a process have?',
    options: ['4', '8', '4096', '2'],
    answer: 2,
    explanation: 'With 4KB pages, the page offset needs 12 bits (2^12 = 4096 = 4KB). With 13-bit logical addresses, 13 - 12 = 1 bit is left for the page number. So 2^1 = 2 pages maximum. Wait — actually with 13 bits total and 12 for offset, only 1 bit for page number = 2 pages. But the answer choice 4096 would be if all 12 bits were page number.'
  },
  {
    q: 'What is the purpose of the TLB (Translation Lookaside Buffer)?',
    options: [
      'To store page tables in disk',
      'A fast hardware cache for recent page table entries, reducing memory access time',
      'To handle page faults',
      'To manage virtual memory swapping'
    ],
    answer: 1,
    explanation: 'The TLB is a small, fast hardware cache (usually 64-1024 entries) that stores recently used page table entries. On a TLB hit, address translation takes only 1 cycle. On a miss, we must access the page table in memory (100+ cycles). With a 99% hit rate, average access time is very close to 1 cycle.'
  },
  {
    q: 'What problem does segmentation solve that paging does not?',
    options: [
      'External fragmentation',
      'Internal fragmentation',
      'It matches the programmer\'s view of memory — code, data, stack as separate logical units',
      'It eliminates the need for address translation'
    ],
    answer: 2,
    explanation: 'Segmentation matches how programmers think about memory — separate segments for code, data, stack, heap, shared libraries. Each segment can grow or shrink independently. Paging is invisible to the programmer and divides memory into fixed-size units with no logical meaning.'
  },
  {
    q: 'What is the main advantage of a multi-level page table over a single-level page table?',
    options: [
      'Faster address translation',
      'Reduces memory needed for the page table itself — only allocate page table pages that are actually used',
      'Eliminates the need for a TLB',
      'Allows larger page sizes'
    ],
    answer: 1,
    explanation: 'A single-level page table for a 32-bit address space with 4KB pages needs 1 million entries (4MB just for the page table). Most of this is unused. A 2-level page table only allocates second-level tables for pages actually in use — saving significant memory for sparse address spaces.'
  },
]

function InfoBox({ children, color }) {
  return (
    <div style={{ background: color + '12', border: '1px solid ' + color + '44', borderLeft: '4px solid ' + color, borderRadius: 10, padding: '16px 20px', marginBottom: 24, fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8 }}>
      {children}
    </div>
  )
}

function LearnMore({ children }) {
  const [open, setOpen] = useState(false)
  return (
    <div style={{ marginTop: 12 }}>
      <button onClick={function() { setOpen(function(o) { return !o }) }} style={{ background: 'none', border: '1px solid #84cc1655', color: '#84cc16', padding: '6px 16px', borderRadius: 20, cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
        {open ? 'Show Less' : 'Learn More (Deep Dive)'}
      </button>
      {open && (
        <div style={{ marginTop: 12, background: 'rgba(132,204,22,0.06)', border: '1px solid #84cc1633', borderRadius: 10, padding: 20, fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.9 }}>
          {children}
        </div>
      )}
    </div>
  )
}

function NavButtons({ prev, prevLabel, next, nextLabel }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 48, paddingTop: 24, borderTop: '1px solid var(--border)' }}>
      {prev ? <button onClick={prev} style={{ background: 'var(--bg-card)', color: 'var(--text-secondary)', border: '1px solid var(--border)', padding: '10px 20px', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>{prevLabel}</button> : <div />}
      {next && <button onClick={next} style={{ background: '#84cc16', color: 'white', border: 'none', padding: '10px 20px', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>{nextLabel}</button>}
    </div>
  )
}

function AddressTranslator() {
  const [pageSize, setPageSize] = useState(4)
  const [logicalAddr, setLogicalAddr] = useState(13)
  const [pageTable] = useState({ 0: 5, 1: 3, 2: 7, 3: 1, 4: 8, 5: 2 })
  const [result, setResult] = useState(null)

  function translate() {
    const pageSizeBytes = pageSize * 1024
    const pageNum = Math.floor(logicalAddr / pageSizeBytes)
    const offset  = logicalAddr % pageSizeBytes
    const frame   = pageTable[pageNum]
    if (frame === undefined) {
      setResult({ error: true, pageNum, offset, msg: 'Page ' + pageNum + ' not in page table — Page Fault!' })
      return
    }
    const physical = frame * pageSizeBytes + offset
    setResult({ error: false, pageNum, offset, frame, physical, pageSizeBytes })
  }

  return (
    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 16, padding: 28, marginBottom: 24 }}>
      <h3 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Address Translation Simulator</h3>
      <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 20 }}>
        Enter a logical address and see it translated to a physical address using the page table.
      </p>

      <div style={{ display: 'flex', gap: 16, marginBottom: 20, flexWrap: 'wrap', alignItems: 'flex-end' }}>
        <div>
          <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 6 }}>Page Size</div>
          <div style={{ display: 'flex', gap: 6 }}>
            {[1, 2, 4, 8].map(function(s) {
              return (
                <button key={s} onClick={function() { setPageSize(s); setResult(null) }} style={{ background: pageSize === s ? '#84cc16' : 'var(--bg-secondary)', color: pageSize === s ? '#000' : 'var(--text-secondary)', border: '1px solid ' + (pageSize === s ? '#84cc16' : 'var(--border)'), padding: '4px 12px', borderRadius: 6, cursor: 'pointer', fontSize: 12, fontWeight: 600 }}>
                  {s}KB
                </button>
              )
            })}
          </div>
        </div>
        <div>
          <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 6 }}>Logical Address (bytes)</div>
          <input type="number" min="0" max="40000" value={logicalAddr} onChange={function(e) { setLogicalAddr(parseInt(e.target.value) || 0); setResult(null) }} style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border)', borderRadius: 6, padding: '6px 12px', color: 'var(--text-primary)', fontSize: 14, width: 140 }} />
        </div>
        <button onClick={translate} style={{ background: '#84cc16', color: '#000', border: 'none', padding: '10px 24px', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 700 }}>
          Translate →
        </button>
      </div>

      <div style={{ marginBottom: 20 }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', marginBottom: 10 }}>Page Table (page → frame):</div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {Object.entries(pageTable).map(function(entry) {
            const pg = parseInt(entry[0]), fr = entry[1]
            const isActive = result && !result.error && result.pageNum === pg
            return (
              <div key={pg} style={{ background: isActive ? '#84cc1622' : 'var(--bg-secondary)', border: '1px solid ' + (isActive ? '#84cc16' : 'var(--border)'), borderRadius: 6, padding: '6px 12px', fontSize: 12, textAlign: 'center' }}>
                <div style={{ color: isActive ? '#84cc16' : '#3b82f6', fontWeight: 700 }}>P{pg}</div>
                <div style={{ color: 'var(--text-muted)', fontSize: 10 }}>↓</div>
                <div style={{ color: isActive ? '#84cc16' : '#f59e0b', fontWeight: 700 }}>F{fr}</div>
              </div>
            )
          })}
        </div>
      </div>

      {result && (
        <div style={{ background: result.error ? '#ef444418' : '#84cc1618', border: '1px solid ' + (result.error ? '#ef4444' : '#84cc16') + '44', borderRadius: 10, padding: 16 }}>
          {result.error
            ? (
              <div style={{ color: '#ef4444', fontWeight: 700, fontSize: 14 }}>{result.msg}</div>
            )
            : (
              <div>
                <div style={{ fontSize: 13, fontWeight: 700, color: '#84cc16', marginBottom: 12 }}>Translation Successful!</div>
                <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
                  {[
                    { label: 'Logical Address', value: logicalAddr, color: '#3b82f6' },
                    { label: 'Page Number', value: 'P' + result.pageNum + ' (addr/' + result.pageSizeBytes + ')', color: '#8b5cf6' },
                    { label: 'Page Offset', value: result.offset + ' bytes', color: '#f59e0b' },
                    { label: 'Frame Number', value: 'F' + result.frame, color: '#10b981' },
                    { label: 'Physical Address', value: result.physical, color: '#84cc16' },
                  ].map(function(item) {
                    return (
                      <div key={item.label} style={{ background: 'var(--bg-secondary)', borderRadius: 8, padding: '10px 14px', textAlign: 'center' }}>
                        <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>{item.label}</div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: item.color }}>{item.value}</div>
                      </div>
                    )
                  })}
                </div>
                <div style={{ marginTop: 12, fontSize: 13, color: 'var(--text-secondary)', fontFamily: 'monospace' }}>
                  Physical = Frame({result.frame}) × PageSize({result.pageSizeBytes}) + Offset({result.offset}) = {result.physical}
                </div>
              </div>
            )}
        </div>
      )}
    </div>
  )
}

function FragmentationDemo() {
  const [type, setType] = useState('external')
  const [memory] = useState([
    { id: 1, size: 100, used: true,  process: 'OS' },
    { id: 2, size: 40,  used: false, process: null },
    { id: 3, size: 80,  used: true,  process: 'P1' },
    { id: 4, size: 20,  used: false, process: null },
    { id: 5, size: 60,  used: true,  process: 'P2' },
    { id: 6, size: 30,  used: false, process: null },
    { id: 7, size: 50,  used: true,  process: 'P3' },
  ])
  const [pagingMemory] = useState([
    { page: 0, frame: 0, size: 4, process: 'P1', full: true },
    { page: 1, frame: 1, size: 4, process: 'P1', full: true },
    { page: 2, frame: 2, size: 4, process: 'P1', full: true, internal: 1 },
    { page: 3, frame: 3, size: 4, process: 'P2', full: true },
    { page: 4, frame: 4, size: 4, process: 'P2', full: false, internal: 3 },
  ])

  const totalFree = memory.filter(function(b) { return !b.used }).reduce(function(s, b) { return s + b.size }, 0)

  return (
    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 16, padding: 28, marginBottom: 24 }}>
      <h3 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Fragmentation Visualizer</h3>
      <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 20 }}>See the difference between external and internal fragmentation.</p>

      <div style={{ display: 'flex', gap: 8, marginBottom: 20 }}>
        {[
          { key: 'external', label: 'External Fragmentation' },
          { key: 'internal', label: 'Internal Fragmentation' },
        ].map(function(t) {
          return (
            <button key={t.key} onClick={function() { setType(t.key) }} style={{ background: type === t.key ? '#84cc1633' : 'var(--bg-secondary)', color: type === t.key ? '#84cc16' : 'var(--text-secondary)', border: '1px solid ' + (type === t.key ? '#84cc16' : 'var(--border)'), padding: '6px 16px', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: type === t.key ? 700 : 400 }}>
              {t.label}
            </button>
          )
        })}
      </div>

      {type === 'external' && (
        <div>
          <InfoBox color="#ef4444">
            <strong>External Fragmentation:</strong> Total free memory is {totalFree}KB but it is split into 3 non-contiguous holes. A process needing 80KB CANNOT run even though {totalFree}KB is free — because no single hole is large enough!
          </InfoBox>
          <div style={{ display: 'flex', gap: 3, marginBottom: 16, alignItems: 'stretch', height: 60 }}>
            {memory.map(function(block) {
              return (
                <div key={block.id} style={{ flex: block.size, background: block.used ? (block.process === 'OS' ? '#6e767122' : '#3b82f622') : '#ef444422', border: '1px solid ' + (block.used ? (block.process === 'OS' ? '#6e7681' : '#3b82f6') : '#ef4444'), borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', minWidth: 20 }}>
                  <div style={{ fontSize: 10, fontWeight: 700, color: block.used ? '#3b82f6' : '#ef4444' }}>{block.used ? block.process : 'FREE'}</div>
                  <div style={{ fontSize: 9, color: 'var(--text-muted)' }}>{block.size}KB</div>
                </div>
              )
            })}
          </div>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
            Free holes: 40KB + 20KB + 30KB = {totalFree}KB total. But a 70KB request FAILS — no contiguous block large enough.
            <br />
            <strong style={{ color: '#f59e0b' }}>Solution: Compaction</strong> — move processes together to create one large free block. Expensive! Requires relocating all processes.
          </div>
        </div>
      )}

      {type === 'internal' && (
        <div>
          <InfoBox color="#f59e0b">
            <strong>Internal Fragmentation:</strong> With 4KB pages, the last page of each process is rarely full. P1 needs 11KB → gets 3 pages (12KB) → 1KB wasted. P2 needs 13KB → gets 4 pages (16KB) → 3KB wasted. Space is wasted INSIDE allocated frames.
          </InfoBox>
          <div style={{ display: 'flex', gap: 6, marginBottom: 16, flexWrap: 'wrap' }}>
            {pagingMemory.map(function(frame) {
              return (
                <div key={frame.frame} style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border)', borderRadius: 8, padding: 10, minWidth: 80, textAlign: 'center' }}>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>Frame {frame.frame}</div>
                  <div style={{ height: 40, background: 'var(--bg-primary)', borderRadius: 4, overflow: 'hidden', position: 'relative' }}>
                    <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: frame.internal ? ((frame.size - frame.internal) / frame.size * 100) + '%' : '100%', background: frame.process === 'P1' ? '#3b82f6' : '#8b5cf6', opacity: 0.7 }} />
                    {frame.internal && (
                      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: (frame.internal / frame.size * 100) + '%', background: '#f59e0b', opacity: 0.5 }} />
                    )}
                  </div>
                  <div style={{ fontSize: 10, color: frame.process === 'P1' ? '#3b82f6' : '#8b5cf6', fontWeight: 700, marginTop: 4 }}>{frame.process}</div>
                  {frame.internal && <div style={{ fontSize: 9, color: '#f59e0b' }}>{frame.internal}KB wasted</div>}
                </div>
              )
            })}
          </div>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
            Yellow = internal fragmentation (wasted space inside frames). Cannot be used by any other process — it belongs to the allocated frame.
            <br />
            <strong style={{ color: '#10b981' }}>Smaller pages</strong> reduce internal fragmentation but increase page table size. Trade-off!
          </div>
        </div>
      )}
    </div>
  )
}

export default function Chapter9() {
  const [active, setActive] = useState('background')
  const [quiz, setQuiz]     = useState({ current: 0, selected: null, answered: false, score: 0, done: false })

  function handleAnswer(i) {
    if (quiz.answered) return
    const correct = i === QUIZ[quiz.current].answer
    setQuiz(function(q) { return { ...q, selected: i, answered: true, score: correct ? q.score + 1 : q.score } })
  }
  function nextQuestion() {
    if (quiz.current + 1 >= QUIZ.length) setQuiz(function(q) { return { ...q, done: true } })
    else setQuiz(function(q) { return { ...q, current: q.current + 1, selected: null, answered: false } })
  }

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-primary)' }}>

      <div style={{ background: 'linear-gradient(135deg, var(--bg-secondary), var(--bg-card))', borderBottom: '1px solid #84cc1644', padding: '48px 60px' }}>
        <div style={{ fontSize: 12, color: '#84cc16', fontWeight: 600, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 }}>Chapter 9</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 12 }}>
          <span style={{ fontSize: 48 }}>💾</span>
          <h1 style={{ fontSize: 40, fontWeight: 800, color: 'var(--text-primary)' }}>Main Memory</h1>
        </div>
        <p style={{ fontSize: 17, color: 'var(--text-secondary)', maxWidth: 700, lineHeight: 1.7 }}>
          How the OS manages physical memory — from address binding to paging, segmentation, fragmentation, and the TLB.
        </p>
        <div style={{ display: 'flex', gap: 10, marginTop: 20, flexWrap: 'wrap' }}>
          {['Address Translation', 'Paging Simulator', 'TLB', 'Fragmentation Demo', 'Segmentation'].map(function(f) {
            return <span key={f} style={{ fontSize: 13, background: 'rgba(132,204,22,0.1)', border: '1px solid #84cc1633', color: '#84cc16', padding: '4px 14px', borderRadius: 20 }}>{f}</span>
          })}
        </div>
      </div>

      <div style={{ display: 'flex' }}>
        <div style={{ width: 240, minWidth: 240, padding: '24px 0', borderRight: '1px solid var(--border)', position: 'sticky', top: 0, height: 'fit-content' }}>
          {sections.map(function(s) {
            return (
              <div key={s.id} onClick={function() { setActive(s.id) }} style={{ padding: '10px 20px', cursor: 'pointer', display: 'flex', gap: 10, alignItems: 'center', fontSize: 13, fontWeight: 500, color: active === s.id ? '#84cc16' : 'var(--text-secondary)', background: active === s.id ? 'rgba(132,204,22,0.1)' : 'transparent', borderLeft: active === s.id ? '3px solid #84cc16' : '3px solid transparent', transition: 'all 0.2s' }}>
                <span>{s.icon}</span><span>{s.title}</span>
              </div>
            )
          })}
        </div>

        <div style={{ flex: 1, padding: '48px 60px', maxWidth: 900 }}>

          {active === 'background' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>9.1 Background</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>Why memory management is needed and the hardware that supports it.</p>

              <InfoBox color="#84cc16">
                Memory is central to the operation of a modern computer. It consists of a large array of bytes, each with its own address. The CPU fetches instructions and data from memory. The OS must manage memory allocation among processes to maximize utilization and protect processes from each other.
              </InfoBox>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 16px' }}>Basic Hardware</h3>
              <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8, marginBottom: 16 }}>
                Each process must have its own separate memory space. Hardware protection uses two registers: the <strong style={{ color: '#84cc16' }}>base register</strong> (lowest legal physical address) and the <strong style={{ color: '#84cc16' }}>limit register</strong> (size of the range). Together they define the legal address space for a process.
              </p>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 24 }}>
                <div style={{ background: 'var(--bg-card)', border: '1px solid #10b98144', borderRadius: 10, padding: 16 }}>
                  <div style={{ fontWeight: 700, color: '#10b981', marginBottom: 8 }}>Base Register</div>
                  <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>Holds the smallest legal physical memory address for the process. Example: base = 300040.</p>
                </div>
                <div style={{ background: 'var(--bg-card)', border: '1px solid #3b82f644', borderRadius: 10, padding: 16 }}>
                  <div style={{ fontWeight: 700, color: '#3b82f6', marginBottom: 8 }}>Limit Register</div>
                  <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>Specifies the size of the range. Example: limit = 120900. So legal addresses are 300040 to 420939.</p>
                </div>
              </div>

              <div style={{ background: '#0d1117', border: '1px solid #30363d', borderRadius: 8, padding: 16, marginBottom: 24 }}>
                <div style={{ fontFamily: 'monospace', fontSize: 12, color: '#e6edf3', lineHeight: 1.9 }}>
                  <div style={{ color: '#8b949e' }}>/* Hardware protection check on EVERY memory access */</div>
                  <div>if (address &lt; base OR address &gt;= base + limit) {'{'}</div>
                  <div style={{ paddingLeft: 20, color: '#ef4444' }}>trap to OS; <span style={{ color: '#8b949e' }}>/* addressing error */</span></div>
                  <div>{'}'} else {'{'}</div>
                  <div style={{ paddingLeft: 20, color: '#10b981' }}>allow memory access;</div>
                  <div>{'}'}</div>
                </div>
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Address Spaces</h3>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
                {[
                  { name: 'Logical Address Space', color: '#3b82f6', desc: 'The set of all logical addresses generated by a program. Also called virtual address space. This is what the CPU and program see. Range: 0 to max.' },
                  { name: 'Physical Address Space', color: '#10b981', desc: 'The set of all physical addresses corresponding to the logical addresses. This is what the memory hardware sees. May be completely different from logical.' },
                ].map(function(s) {
                  return (
                    <div key={s.name} style={{ background: 'var(--bg-card)', border: '1px solid ' + s.color + '44', borderRadius: 10, padding: 16 }}>
                      <div style={{ fontWeight: 700, color: s.color, marginBottom: 8 }}>{s.name}</div>
                      <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{s.desc}</p>
                    </div>
                  )
                })}
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>The MMU — Memory Management Unit</h3>
              <InfoBox color="#8b5cf6">
                The <strong>MMU</strong> is hardware that maps virtual (logical) addresses to physical addresses at runtime. In the simplest scheme, the MMU adds the base register value to every logical address generated by the user process. The user program never sees the real physical addresses — it only deals with logical addresses.
              </InfoBox>

              <LearnMore>
                <strong style={{ color: 'var(--text-primary)' }}>Why separate logical and physical addresses?</strong> It allows the OS to relocate processes anywhere in physical memory without the process knowing. A process compiled to run at address 0 can actually run at address 300040 — the MMU handles the translation. It also allows virtual memory — processes can have address spaces larger than physical memory, with the OS swapping pages in and out as needed.
                <br /><br />
                <strong style={{ color: 'var(--text-primary)' }}>Dynamic Loading:</strong> A routine is not loaded into memory until it is called. All routines are kept on disk in a relocatable load format. The main program is loaded and runs. When a routine needs to call another routine, the loader checks if it is already loaded — if not, loads it. Better memory utilization when large amounts of code are needed infrequently (e.g., error handling routines).
              </LearnMore>

              <NavButtons next={function() { setActive('binding') }} nextLabel="9.2 Address Binding →" />
            </div>
          )}

          {active === 'binding' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>9.2 Address Binding</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>When and how addresses in a program get mapped to memory locations.</p>

              <InfoBox color="#3b82f6">
                A program goes through several steps before running. Addresses in the source code are symbolic (variable names). These must be <strong>bound</strong> to actual memory addresses at some point. Binding can happen at three different times.
              </InfoBox>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 16px' }}>Three Stages of Address Binding</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 24 }}>
                {[
                  {
                    stage: 'Compile Time',
                    color: '#ef4444',
                    desc: 'If you know at compile time exactly where the process will reside in memory, absolute code can be generated. If the location changes, the code must be recompiled.',
                    example: 'MS-DOS .COM files. Old embedded systems. Very inflexible.',
                    when: 'Compile time',
                  },
                  {
                    stage: 'Load Time',
                    color: '#f59e0b',
                    desc: 'If not known at compile time, the compiler generates relocatable code. Final binding is delayed until load time. If the starting address changes, only need to reload.',
                    example: 'Early UNIX programs. Static libraries.',
                    when: 'When program is loaded into memory',
                  },
                  {
                    stage: 'Execution Time',
                    color: '#10b981',
                    desc: 'Binding delayed until runtime. The process can be moved during execution from one memory segment to another. Requires hardware support (MMU). Used by most modern OSes.',
                    example: 'All modern OSes — Linux, Windows, macOS.',
                    when: 'During program execution (dynamic)',
                  },
                ].map(function(s, i) {
                  return (
                    <div key={s.stage} style={{ background: 'var(--bg-card)', border: '1px solid ' + s.color + '44', borderLeft: '4px solid ' + s.color, borderRadius: 10, padding: 20 }}>
                      <div style={{ display: 'flex', gap: 12, alignItems: 'center', marginBottom: 8 }}>
                        <div style={{ width: 26, height: 26, borderRadius: '50%', background: s.color, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 700, color: '#000', flexShrink: 0 }}>{i + 1}</div>
                        <div style={{ fontWeight: 700, color: s.color, fontSize: 15 }}>{s.stage} Binding</div>
                        <div style={{ fontSize: 11, color: 'var(--text-muted)', background: s.color + '22', padding: '2px 8px', borderRadius: 10 }}>{s.when}</div>
                      </div>
                      <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 6 }}>{s.desc}</p>
                      <div style={{ fontSize: 12, color: 'var(--text-muted)', fontStyle: 'italic' }}>Examples: {s.example}</div>
                    </div>
                  )
                })}
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>From Source to Running Process</h3>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap', marginBottom: 16 }}>
                {[
                  { step: 'Source Code', color: '#6e7681', desc: 'Symbolic addresses' },
                  { step: '↓ Compiler', color: '#3b82f6', desc: '' },
                  { step: 'Object Module', color: '#8b5cf6', desc: 'Relocatable addresses' },
                  { step: '↓ Linker', color: '#3b82f6', desc: '' },
                  { step: 'Executable', color: '#f59e0b', desc: 'Virtual addresses' },
                  { step: '↓ Loader', color: '#3b82f6', desc: '' },
                  { step: 'In Memory', color: '#10b981', desc: 'Physical addresses' },
                ].map(function(s, i) {
                  if (s.step.startsWith('↓')) {
                    return <div key={i} style={{ fontSize: 18, color: '#3b82f6' }}>{s.step}</div>
                  }
                  return (
                    <div key={i} style={{ background: s.color + '22', border: '1px solid ' + s.color + '44', borderRadius: 8, padding: '8px 14px', textAlign: 'center' }}>
                      <div style={{ fontWeight: 700, color: s.color, fontSize: 12 }}>{s.step}</div>
                      {s.desc && <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>{s.desc}</div>}
                    </div>
                  )
                })}
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Dynamic Linking</h3>
              <InfoBox color="#f59e0b">
                <strong>Static linking</strong>: library code is copied into the executable at link time. Large executables, each process has its own copy of library code.
                <br /><br />
                <strong>Dynamic linking</strong>: linking postponed until execution time. Small stub in code calls the DLL/shared library. Library loaded once and shared by all processes using it. Saves memory and allows library updates without recompiling.
              </InfoBox>

              <LearnMore>
                <strong style={{ color: 'var(--text-primary)' }}>Shared libraries in Linux (ELF):</strong> Linux uses ELF (Executable and Linkable Format). Shared libraries (.so files) are loaded by ld.so (the dynamic linker). The GOT (Global Offset Table) and PLT (Procedure Linkage Table) enable lazy binding — library functions are resolved on first call, not at load time. This speeds up program startup. Run ldd on any executable to see its dynamic library dependencies.
                <br /><br />
                <strong style={{ color: 'var(--text-primary)' }}>Position-Independent Code (PIC):</strong> Shared libraries must be compilable as PIC — code that executes correctly regardless of where it is loaded in memory. PIC uses relative addressing and the GOT. Without PIC, each process loading a shared library would need its own copy at a fixed address — defeating the purpose of sharing.
              </LearnMore>

              <NavButtons prev={function() { setActive('background') }} prevLabel="← 9.1 Background" next={function() { setActive('contiguous') }} nextLabel="9.3 Contiguous Allocation →" />
            </div>
          )}

          {active === 'contiguous' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>9.3 Contiguous Memory Allocation</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>The simplest memory allocation strategy — and why it leads to fragmentation.</p>

              <InfoBox color="#f59e0b">
                In contiguous allocation, each process is contained in a single contiguous section of memory. Memory is divided into two partitions: the OS (usually in low memory) and user processes. Multiple partitions allow multiple processes in memory simultaneously.
              </InfoBox>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 16px' }}>Variable Partition Scheme</h3>
              <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8, marginBottom: 16 }}>
                The OS maintains a table of free and allocated memory partitions (holes). When a process arrives, it is allocated a hole large enough to contain it. When a process terminates, its memory is released as a free hole.
              </p>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Allocation Algorithms</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 24 }}>
                {[
                  { name: 'First Fit', color: '#3b82f6', desc: 'Allocate the FIRST hole that is big enough. Scan from beginning (or from where last search ended). Fast — stops at first fit.', pro: 'Fast', con: 'Can leave small unusable holes at start' },
                  { name: 'Best Fit', color: '#10b981', desc: 'Allocate the SMALLEST hole that is big enough. Must search entire list (unless sorted by size). Produces smallest leftover hole.', pro: 'Minimizes leftover space', con: 'Slow, produces many tiny holes' },
                  { name: 'Worst Fit', color: '#ef4444', desc: 'Allocate the LARGEST hole. Must search entire list. Produces largest leftover hole — which might be usable.', pro: 'Large leftover holes', con: 'Slow, wastes large holes, performs worst in practice' },
                ].map(function(a) {
                  return (
                    <div key={a.name} style={{ background: 'var(--bg-card)', border: '1px solid ' + a.color + '33', borderRadius: 10, padding: 16 }}>
                      <div style={{ display: 'flex', gap: 12, alignItems: 'center', marginBottom: 8, flexWrap: 'wrap' }}>
                        <div style={{ fontWeight: 700, color: a.color, fontSize: 14 }}>{a.name}</div>
                        <span style={{ fontSize: 12, background: '#10b98118', color: '#10b981', padding: '2px 8px', borderRadius: 10 }}>Pro: {a.pro}</span>
                        <span style={{ fontSize: 12, background: '#ef444418', color: '#ef4444', padding: '2px 8px', borderRadius: 10 }}>Con: {a.con}</span>
                      </div>
                      <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{a.desc}</p>
                    </div>
                  )
                })}
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Fragmentation</h3>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 24 }}>
                <div style={{ background: 'var(--bg-card)', border: '1px solid #ef444444', borderRadius: 10, padding: 16 }}>
                  <div style={{ fontWeight: 700, color: '#ef4444', marginBottom: 8 }}>External Fragmentation</div>
                  <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                    Enough total memory exists to satisfy a request, but it is not contiguous — scattered in small holes. Fixed with <strong>compaction</strong> (shuffle memory to consolidate holes) — expensive! Or use non-contiguous allocation (paging).
                  </p>
                </div>
                <div style={{ background: 'var(--bg-card)', border: '1px solid #f59e0b44', borderRadius: 10, padding: 16 }}>
                  <div style={{ fontWeight: 700, color: '#f59e0b', marginBottom: 8 }}>Internal Fragmentation</div>
                  <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                    Allocated memory may be larger than requested — the difference is wasted internally. Example: holes are allocated in multiples of 4 bytes. A 18-byte request gets 20 bytes — 2 bytes wasted.
                  </p>
                </div>
              </div>

              <FragmentationDemo />

              <LearnMore>
                <strong style={{ color: 'var(--text-primary)' }}>50-percent rule:</strong> With first-fit allocation, statistical analysis shows that given N allocated blocks, another 0.5N blocks will be lost to fragmentation. So one-third of memory may be unusable — this is why contiguous allocation was replaced by paging in modern OSes.
                <br /><br />
                <strong style={{ color: 'var(--text-primary)' }}>Compaction:</strong> Moving all processes to one end of memory and all free space to the other. Requires all processes to be relocatable at execution time (execution-time binding). Very expensive — must copy all process memory and update all base registers. Some systems defer compaction to times of low activity. Modern systems avoid the problem entirely using paging.
              </LearnMore>

              <NavButtons prev={function() { setActive('binding') }} prevLabel="← 9.2 Binding" next={function() { setActive('paging') }} nextLabel="9.4 Paging →" />
            </div>
          )}

          {active === 'paging' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>9.4 Paging</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>The fundamental memory management technique used by all modern OSes.</p>

              <InfoBox color="#84cc16">
                <strong>Paging</strong> allows a process's physical address space to be <strong>non-contiguous</strong>. Physical memory is divided into fixed-size blocks called <strong>frames</strong>. Logical memory is divided into same-size blocks called <strong>pages</strong>. No external fragmentation! Only internal fragmentation in the last page.
              </InfoBox>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 16px' }}>Key Concepts</h3>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginBottom: 24 }}>
                {[
                  { name: 'Frame', color: '#f59e0b', desc: 'Fixed-size block of physical memory. Frame size is a power of 2 (typically 4KB). Frames are numbered 0, 1, 2...' },
                  { name: 'Page', color: '#3b82f6', desc: 'Fixed-size block of logical memory. Same size as a frame. Pages are numbered 0, 1, 2... per process.' },
                  { name: 'Page Table', color: '#10b981', desc: 'Per-process table maintained by OS. Maps each page number to its frame number. Stored in main memory.' },
                  { name: 'Page Number (p)', color: '#8b5cf6', desc: 'Upper bits of logical address. Index into page table to find the frame number.' },
                  { name: 'Page Offset (d)', color: '#ef4444', desc: 'Lower bits of logical address. Offset within the page/frame. Unchanged in translation.' },
                  { name: 'Frame Number (f)', color: '#84cc16', desc: 'From page table. Combined with offset to form physical address: f * page_size + d.' },
                ].map(function(c) {
                  return (
                    <div key={c.name} style={{ background: 'var(--bg-card)', border: '1px solid ' + c.color + '44', borderRadius: 8, padding: 14 }}>
                      <div style={{ fontWeight: 700, color: c.color, marginBottom: 6, fontSize: 13 }}>{c.name}</div>
                      <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{c.desc}</div>
                    </div>
                  )
                })}
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Address Translation</h3>
              <InfoBox color="#3b82f6">
                Logical address = page number (p) + page offset (d)
                <br />
                Physical address = frame number (f) + page offset (d)
                <br /><br />
                If page size = 2^n bytes, then the lower n bits of logical address = offset (d), and upper bits = page number (p).
                <br />
                Physical address = page_table[p] * 2^n + d
              </InfoBox>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Example</h3>
              <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 10, padding: 16, marginBottom: 24 }}>
                <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 10 }}>Page size = 4 bytes. Logical address space = 16 bytes (4 pages). Physical memory = 32 bytes (8 frames).</div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                  <div style={{ background: '#0d1117', borderRadius: 8, padding: 12 }}>
                    <div style={{ fontSize: 11, color: '#3b82f6', marginBottom: 6 }}>Logical Address 6 = ?</div>
                    <div style={{ fontFamily: 'monospace', fontSize: 12, color: '#e6edf3', lineHeight: 1.8 }}>
                      <div>Page size = 4 = 2^2</div>
                      <div>Page number = 6 / 4 = 1</div>
                      <div>Offset = 6 % 4 = 2</div>
                      <div>Frame (from table) = 5</div>
                      <div style={{ color: '#10b981' }}>Physical = 5*4 + 2 = 22</div>
                    </div>
                  </div>
                  <div style={{ background: '#0d1117', borderRadius: 8, padding: 12 }}>
                    <div style={{ fontSize: 11, color: '#f59e0b', marginBottom: 6 }}>Page Table:</div>
                    <div style={{ fontFamily: 'monospace', fontSize: 12, color: '#e6edf3', lineHeight: 1.8 }}>
                      <div>Page 0 → Frame 5</div>
                      <div style={{ color: '#84cc16' }}>Page 1 → Frame 5 ← used</div>
                      <div>Page 2 → Frame 1</div>
                      <div>Page 3 → Frame 2</div>
                    </div>
                  </div>
                </div>
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Interactive Address Translator</h3>
              <AddressTranslator />

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Page Table Implementation</h3>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
                <div style={{ background: 'var(--bg-card)', border: '1px solid #10b98144', borderRadius: 10, padding: 16 }}>
                  <div style={{ fontWeight: 700, color: '#10b981', marginBottom: 8 }}>Page Table Base Register (PTBR)</div>
                  <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>Points to the page table in memory. On context switch, save/restore PTBR. Simple — only one register to save. Problem: every data/instruction access requires TWO memory accesses — one for page table, one for actual data.</p>
                </div>
                <div style={{ background: 'var(--bg-card)', border: '1px solid #8b5cf644', borderRadius: 10, padding: 16 }}>
                  <div style={{ fontWeight: 700, color: '#8b5cf6', marginBottom: 8 }}>Page Table Length Register (PTLR)</div>
                  <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>Indicates size of the page table. Used to validate page numbers — if page number exceeds PTLR, it is an illegal address (segmentation fault).</p>
                </div>
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Memory Protection with Paging</h3>
              <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8, marginBottom: 16 }}>
                Each page table entry has a <strong style={{ color: '#84cc16' }}>valid-invalid bit</strong>. Valid = page is in the process's logical address space. Invalid = page is not in the address space — accessing it causes a trap (segfault). Additional protection bits: read-only, read-write, execute-only.
              </p>

              <LearnMore>
                <strong style={{ color: 'var(--text-primary)' }}>Shared pages:</strong> With paging, it is easy to share code between processes. If two processes run the same program, the read-only code pages can be mapped to the same frames. Example: 40 users running a text editor with 150KB code + 50KB data. Without sharing: 40 * 200KB = 8000KB. With sharing: 150KB (shared code) + 40 * 50KB (private data) = 2150KB. Huge savings!
                <br /><br />
                <strong style={{ color: 'var(--text-primary)' }}>Copy-on-Write (COW) with paging:</strong> After fork(), parent and child share all pages marked read-only. When either tries to write, the OS creates a private copy of that page — only then is it duplicated. If the child immediately calls exec(), no pages are ever copied. This makes fork() + exec() extremely fast on modern systems.
              </LearnMore>

              <NavButtons prev={function() { setActive('contiguous') }} prevLabel="← 9.3 Contiguous" next={function() { setActive('tlb') }} nextLabel="9.5 TLB →" />
            </div>
          )}

          {active === 'tlb' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>9.5 TLB and Performance</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>The hardware cache that makes paging fast.</p>

              <InfoBox color="#f59e0b">
                The problem with paging: every memory access requires TWO memory references (one for the page table, one for the actual data). Solution: the <strong>Translation Lookaside Buffer (TLB)</strong> — a small, fast hardware cache that stores recent page table entries.
              </InfoBox>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 16px' }}>How the TLB Works</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 24 }}>
                {[
                  { n: 1, color: '#3b82f6', text: 'CPU generates logical address with page number p' },
                  { n: 2, color: '#f59e0b', text: 'Check TLB: is page p in the TLB? (TLB lookup — very fast, ~1 cycle)' },
                  { n: 3, color: '#10b981', text: 'TLB HIT: Get frame number directly. Physical address = frame * size + offset. ONE memory access total.' },
                  { n: 4, color: '#ef4444', text: 'TLB MISS: Access page table in memory (slow — 100s of cycles). Get frame number. Update TLB with this entry. TWO memory accesses total.' },
                ].map(function(s) {
                  return (
                    <div key={s.n} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                      <div style={{ width: 26, height: 26, borderRadius: '50%', background: s.color, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 700, color: '#000', flexShrink: 0 }}>{s.n}</div>
                      <div style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6, paddingTop: 3 }}>{s.text}</div>
                    </div>
                  )
                })}
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Effective Access Time (EAT)</h3>
              <InfoBox color="#10b981">
                Hit ratio (h) = fraction of page lookups found in TLB.
                <br />Memory access time = 100ns (typical).
                <br /><br />
                <strong>EAT = h × (TLB time + memory) + (1-h) × (TLB time + 2 × memory)</strong>
                <br /><br />
                Example: TLB time = 20ns, memory = 100ns, h = 80%:
                <br />EAT = 0.8 × (120) + 0.2 × (220) = 96 + 44 = <strong>140ns</strong> (vs 220ns without TLB)
              </InfoBox>

              <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 10, padding: 16, marginBottom: 24 }}>
                <div style={{ fontWeight: 700, marginBottom: 12, fontSize: 14 }}>EAT with different hit ratios:</div>
                {[
                  { h: 80, eat: 140 },
                  { h: 90, eat: 130 },
                  { h: 99, eat: 121 },
                  { h: 99.9, eat: 120.1 },
                ].map(function(row) {
                  return (
                    <div key={row.h} style={{ display: 'flex', gap: 16, alignItems: 'center', marginBottom: 8 }}>
                      <div style={{ fontSize: 13, color: 'var(--text-muted)', minWidth: 100 }}>Hit ratio: {row.h}%</div>
                      <div style={{ flex: 1, background: 'var(--bg-secondary)', borderRadius: 4, height: 12 }}>
                        <div style={{ height: '100%', background: '#84cc16', borderRadius: 4, width: ((220 - row.eat) / 120 * 100) + '%', transition: 'all 0.3s' }} />
                      </div>
                      <div style={{ fontSize: 13, fontWeight: 700, color: '#84cc16', minWidth: 60 }}>{row.eat}ns</div>
                    </div>
                  )
                })}
                <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 8 }}>Without TLB: 220ns. With TLB (99% hit): effectively same as no page table overhead.</div>
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>TLB Details</h3>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
                {[
                  { name: 'Size', color: '#3b82f6', desc: 'Typically 64 to 1024 entries. Intel i7: 128 L1 TLB entries for data, 128 for instructions. Modern CPUs have 2-level TLBs.' },
                  { name: 'ASID', color: '#8b5cf6', desc: 'Address Space Identifier — tags each TLB entry with which process it belongs to. Allows TLB to hold entries from multiple processes without flushing on context switch.' },
                  { name: 'Replacement', color: '#f59e0b', desc: 'TLB uses LRU or random replacement when full. Random is often used in hardware for simplicity.' },
                  { name: 'Flush', color: '#ef4444', desc: 'TLB flushed on context switch (without ASID). On modern CPUs with ASID, only invalidate entries for the switching process.' },
                ].map(function(d) {
                  return (
                    <div key={d.name} style={{ background: 'var(--bg-card)', border: '1px solid ' + d.color + '33', borderRadius: 8, padding: 14 }}>
                      <div style={{ fontWeight: 700, color: d.color, marginBottom: 6, fontSize: 13 }}>{d.name}</div>
                      <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{d.desc}</div>
                    </div>
                  )
                })}
              </div>

              <LearnMore>
                <strong style={{ color: 'var(--text-primary)' }}>Why TLB hit rates are so high:</strong> Locality of reference. Most programs exhibit temporal locality (recently accessed pages will be accessed again soon) and spatial locality (pages near recently accessed pages are likely to be accessed). A program loop accesses the same code pages repeatedly — TLB entry loaded once, hit every iteration. 64-1024 entries is enough to cover most active working sets.
                <br /><br />
                <strong style={{ color: 'var(--text-primary)' }}>Spectre and Meltdown — TLB security:</strong> The 2018 Spectre and Meltdown vulnerabilities exploited CPU speculative execution and cache timing (including TLB). The OS patches (KPTI — Kernel Page-Table Isolation) required separating kernel and user page tables, causing TLB flushes on every kernel entry/exit. This reduced performance by 5-30% on I/O-heavy workloads — showing how critical TLB performance is.
              </LearnMore>

              <NavButtons prev={function() { setActive('paging') }} prevLabel="← 9.4 Paging" next={function() { setActive('structure') }} nextLabel="9.6 Page Table Structure →" />
            </div>
          )}

          {active === 'structure' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>9.6 Page Table Structure</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>How to handle large address spaces efficiently.</p>

              <InfoBox color="#8b5cf6">
                With a 32-bit address space and 4KB pages, a page table has 1 million entries (4MB per process just for page tables!). With 64-bit address spaces, it would be impossibly large. Several structures solve this.
              </InfoBox>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 20, marginBottom: 24 }}>

                <div style={{ background: 'var(--bg-card)', border: '1px solid #3b82f644', borderRadius: 12, padding: 24 }}>
                  <h4 style={{ fontSize: 16, fontWeight: 700, color: '#3b82f6', marginBottom: 12 }}>Hierarchical / Multi-Level Page Tables</h4>
                  <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 12 }}>
                    Break the page table into multiple levels. Only allocate second-level tables for pages actually in use. A 2-level page table divides the page number into two parts: outer page number (p1) and inner page number (p2).
                  </p>
                  <div style={{ background: '#0d1117', borderRadius: 8, padding: 12, marginBottom: 8 }}>
                    <div style={{ fontFamily: 'monospace', fontSize: 12, color: '#e6edf3', lineHeight: 1.9 }}>
                      <div style={{ color: '#8b949e' }}>/* 32-bit address, 4KB pages, 2-level */</div>
                      <div>logical address: [p1 (10 bits)][p2 (10 bits)][offset (12 bits)]</div>
                      <div></div>
                      <div>outer_table = page_directory[p1]</div>
                      <div>frame = outer_table[p2]</div>
                      <div>physical = frame * 4096 + offset</div>
                    </div>
                  </div>
                  <div style={{ fontSize: 13, color: 'var(--text-muted)' }}>Trade-off: saves memory for sparse address spaces but needs MORE memory accesses (3 for 2-level). TLB hides this cost.</div>
                </div>

                <div style={{ background: 'var(--bg-card)', border: '1px solid #10b98144', borderRadius: 12, padding: 24 }}>
                  <h4 style={{ fontSize: 16, fontWeight: 700, color: '#10b981', marginBottom: 12 }}>Hashed Page Tables</h4>
                  <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
                    Virtual page number is hashed into a hash table. Common for address spaces larger than 32 bits. Each element in the hash table is a linked list of page numbers that hash to the same location. Search the chain for a matching page.
                  </p>
                </div>

                <div style={{ background: 'var(--bg-card)', border: '1px solid #f59e0b44', borderRadius: 12, padding: 24 }}>
                  <h4 style={{ fontSize: 16, fontWeight: 700, color: '#f59e0b', marginBottom: 12 }}>Inverted Page Tables</h4>
                  <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 12 }}>
                    Instead of one entry per logical page per process, have ONE entry per physical frame. Entry contains the process ID and logical page mapped to that frame. Only ONE page table in the entire system regardless of number of processes. IBM PowerPC and UltraSPARC use this.
                  </p>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                    <div>
                      <div style={{ fontSize: 12, color: '#10b981', fontWeight: 600, marginBottom: 4 }}>Advantage:</div>
                      <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>Dramatically reduces memory needed for page table (one entry per frame, not per logical page).</div>
                    </div>
                    <div>
                      <div style={{ fontSize: 12, color: '#ef4444', fontWeight: 600, marginBottom: 4 }}>Disadvantage:</div>
                      <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>Searching takes O(n) time where n = number of frames. Need hash to speed up. Difficult to implement shared memory.</div>
                    </div>
                  </div>
                </div>

              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Comparison</h3>
              <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                  <thead>
                    <tr style={{ background: 'var(--bg-secondary)' }}>
                      {['Structure', 'Memory Use', 'Lookup Time', 'Used By'].map(function(h) {
                        return <th key={h} style={{ padding: '8px 14px', textAlign: 'left', color: 'var(--text-muted)', borderBottom: '1px solid var(--border)' }}>{h}</th>
                      })}
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      ['Single-level', 'High (4MB/process)', 'O(1)', 'Simple systems'],
                      ['2-level', 'Low (sparse spaces)', 'O(1) + extra accesses', 'x86-32, Linux'],
                      ['4-level', 'Very low', 'O(1) + 4 accesses', 'x86-64, Linux/Windows'],
                      ['Hashed', 'Low', 'O(1) average', 'SPARC, some 64-bit'],
                      ['Inverted', 'Lowest (per frame)', 'O(n) → O(1) with hash', 'PowerPC, UltraSPARC'],
                    ].map(function(row) {
                      return (
                        <tr key={row[0]} style={{ borderBottom: '1px solid var(--border)' }}>
                          {row.map(function(cell, i) {
                            return <td key={i} style={{ padding: '8px 14px', color: i === 0 ? '#84cc16' : 'var(--text-secondary)', fontWeight: i === 0 ? 700 : 400 }}>{cell}</td>
                          })}
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>

              <LearnMore>
                <strong style={{ color: 'var(--text-primary)' }}>x86-64 uses 4-level paging:</strong> 64-bit address space is 16 exabytes but only 48 bits are used (256TB). The 48-bit virtual address is split: [9 bits PML4][9 bits PDPT][9 bits PD][9 bits PT][12 bits offset]. Four levels of page table lookup + TLB. AMD/Intel recently added 5-level paging (57-bit virtual addresses = 128 petabytes) for extreme servers.
                <br /><br />
                <strong style={{ color: 'var(--text-primary)' }}>Huge pages (superpages):</strong> Most OSes support 2MB and 1GB pages in addition to 4KB. Huge pages reduce TLB pressure (one TLB entry covers 2MB instead of 4KB). Used for database buffers, virtual machine memory, HPC workloads. Linux: HugeTLBFS and Transparent Huge Pages (THP). Can improve performance by 10-30% for memory-intensive applications.
              </LearnMore>

              <NavButtons prev={function() { setActive('tlb') }} prevLabel="← 9.5 TLB" next={function() { setActive('segmentation') }} nextLabel="9.7 Segmentation →" />
            </div>
          )}

          {active === 'segmentation' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>9.7 Segmentation</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>Memory management that matches the programmer's view of memory.</p>

              <InfoBox color="#ef4444">
                Users think of memory as a collection of variable-size segments — not as one flat array of bytes. A C program has: code segment, stack segment, heap segment, data segment, and possibly shared library segments. <strong>Segmentation</strong> supports this user view of memory.
              </InfoBox>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 16px' }}>Segmentation Architecture</h3>
              <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8, marginBottom: 16 }}>
                A logical address consists of a <strong style={{ color: '#3b82f6' }}>segment number (s)</strong> and an <strong style={{ color: '#f59e0b' }}>offset (d)</strong>. The <strong style={{ color: '#10b981' }}>segment table</strong> maps each segment to its base address and limit (size).
              </p>

              <div style={{ background: '#0d1117', border: '1px solid #ef444444', borderRadius: 8, padding: 14, marginBottom: 24 }}>
                <div style={{ fontFamily: 'monospace', fontSize: 12, color: '#e6edf3', lineHeight: 1.9 }}>
                  <div style={{ color: '#8b949e' }}>/* Segment table entry */</div>
                  <div>segment_table[s].base  = starting physical address</div>
                  <div>segment_table[s].limit = length of segment</div>
                  <div></div>
                  <div style={{ color: '#8b949e' }}>/* Address translation */</div>
                  <div>if (d &lt; 0 OR d &gt;= segment_table[s].limit)</div>
                  <div style={{ paddingLeft: 20, color: '#ef4444' }}>trap; <span style={{ color: '#8b949e' }}>/* segmentation fault */</span></div>
                  <div>else</div>
                  <div style={{ paddingLeft: 20, color: '#10b981' }}>physical = segment_table[s].base + d;</div>
                </div>
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Typical Segments in a C Program</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 24 }}>
                {[
                  { seg: 'Segment 0: Code', color: '#3b82f6', base: '1400', limit: '1000', prot: 'Read + Execute' },
                  { seg: 'Segment 1: Stack', color: '#10b981', base: '6300', limit: '400',  prot: 'Read + Write' },
                  { seg: 'Segment 2: Heap', color: '#f59e0b', base: '4300', limit: '1100', prot: 'Read + Write' },
                  { seg: 'Segment 3: Data', color: '#8b5cf6', base: '3200', limit: '600',  prot: 'Read + Write' },
                  { seg: 'Segment 4: Shared lib', color: '#ef4444', base: '7000', limit: '1000', prot: 'Read + Execute (shared)' },
                ].map(function(s) {
                  return (
                    <div key={s.seg} style={{ background: 'var(--bg-card)', border: '1px solid ' + s.color + '33', borderRadius: 8, padding: '10px 16px', display: 'flex', gap: 16, alignItems: 'center', flexWrap: 'wrap' }}>
                      <div style={{ fontWeight: 700, color: s.color, fontSize: 13, minWidth: 160 }}>{s.seg}</div>
                      <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Base: {s.base}</div>
                      <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Limit: {s.limit}</div>
                      <div style={{ fontSize: 12, color: s.color, background: s.color + '18', padding: '2px 8px', borderRadius: 10 }}>{s.prot}</div>
                    </div>
                  )
                })}
              </div>

              <h3 style={{ fontSize: 18, fontWeight: 700, margin: '24px 0 12px' }}>Segmentation vs Paging</h3>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
                <div style={{ background: 'var(--bg-card)', border: '1px solid #84cc1644', borderRadius: 10, padding: 16 }}>
                  <div style={{ fontWeight: 700, color: '#84cc16', marginBottom: 8 }}>Segmentation Advantages</div>
                  <ul style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.8, paddingLeft: 16 }}>
                    <li>Matches programmer's view</li>
                    <li>Easy to share segments (shared libraries)</li>
                    <li>Each segment can grow/shrink independently</li>
                    <li>Fine-grained protection per segment</li>
                  </ul>
                </div>
                <div style={{ background: 'var(--bg-card)', border: '1px solid #ef444444', borderRadius: 10, padding: 16 }}>
                  <div style={{ fontWeight: 700, color: '#ef4444', marginBottom: 8 }}>Segmentation Disadvantages</div>
                  <ul style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.8, paddingLeft: 16 }}>
                    <li>External fragmentation (variable sizes)</li>
                    <li>Compaction may be needed</li>
                    <li>Complex memory allocation</li>
                    <li>Segfaults are hard to debug</li>
                  </ul>
                </div>
              </div>

              <InfoBox color="#f59e0b">
                <strong>Intel x86:</strong> Uses segmentation (segment registers CS, DS, SS, ES, FS, GS) combined with paging. Linux and Windows largely ignore the segmentation layer — all segments are set to base 0 and max limit, effectively making segmentation transparent. Paging does all the real work.
              </InfoBox>

              <LearnMore>
                <strong style={{ color: 'var(--text-primary)' }}>Segmentation faults explained:</strong> A segfault (SIGSEGV) occurs when a program accesses memory outside its valid segments or violates segment permissions. Common causes: null pointer dereference (address 0 is not mapped), buffer overflow (write beyond array end into another segment), use-after-free (accessing freed memory), stack overflow (stack segment exhausted). The MMU hardware detects the violation and sends SIGSEGV to the process.
                <br /><br />
                <strong style={{ color: 'var(--text-primary)' }}>Segmentation with paging (Intel x86):</strong> Intel's protected mode combines both. Logical address → segmentation unit → linear address → paging unit → physical address. In practice, modern 64-bit x86 (long mode) has very limited segmentation — only FS and GS segments are meaningful (used for thread-local storage and per-CPU data in the kernel). Pure paging handles all address translation.
              </LearnMore>

              <NavButtons prev={function() { setActive('structure') }} prevLabel="← 9.6 Page Table Structure" next={function() { setActive('simulator') }} nextLabel="Simulators →" />
            </div>
          )}

          {active === 'simulator' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Memory Management Simulators</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>Interactive tools for address translation and fragmentation.</p>

              <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16 }}>Address Translation (Paging)</h3>
              <AddressTranslator />

              <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16, marginTop: 32 }}>Fragmentation Visualizer</h3>
              <FragmentationDemo />

              <NavButtons prev={function() { setActive('segmentation') }} prevLabel="← 9.7 Segmentation" next={function() { setActive('lab') }} nextLabel="Lab →" />
            </div>
          )}

          {active === 'lab' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Lab — Memory in Code</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>Explore memory management concepts through code and the terminal.</p>

              <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 8, color: '#84cc16' }}>Lab 1 — Memory Layout in Python</h3>
              <p style={{ fontSize: 14, color: 'var(--text-secondary)', marginBottom: 16, lineHeight: 1.7 }}>
                Inspect memory addresses of variables and see the layout of a process.
              </p>
              <CodeEditor defaultLang="python" height={280} />

              <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 8, marginTop: 32, color: '#3b82f6' }}>Lab 2 — Explore Memory in Terminal</h3>
              <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 10, padding: 16, marginBottom: 16 }}>
                {[
                  ['cat /proc/meminfo',       'Show system memory info (total, free, cached)'],
                  ['cat /proc/self/maps',      'Show memory map of current process'],
                  ['cat /proc/1/maps',         'Show memory map of process 1 (init/systemd)'],
                  ['free -h',                  'Human-readable memory usage'],
                  ['vmstat',                   'Virtual memory statistics'],
                  ['cat /proc/self/status',    'Memory stats for current process (VmRSS, VmSize)'],
                  ['getconf PAGE_SIZE',        'Show system page size in bytes'],
                ].map(function(item) {
                  return (
                    <div key={item[0]} style={{ display: 'flex', gap: 16, marginBottom: 10, alignItems: 'center' }}>
                      <code style={{ background: '#0d1117', color: '#3fb950', padding: '3px 10px', borderRadius: 4, fontSize: 11, fontFamily: 'monospace', minWidth: 200, flexShrink: 0 }}>{item[0]}</code>
                      <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{item[1]}</span>
                    </div>
                  )
                })}
              </div>
              <Terminal />

              <NavButtons prev={function() { setActive('simulator') }} prevLabel="← Simulators" next={function() { setActive('quiz') }} nextLabel="Take the Quiz →" />
            </div>
          )}

          {active === 'quiz' && (
            <div>
              <h2 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Test Your Knowledge</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 15 }}>6 questions covering all of Chapter 9.</p>

              {!quiz.done
                ? (
                  <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 16, padding: 32 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                      <span style={{ fontSize: 13, color: 'var(--text-muted)' }}>Question {quiz.current + 1} of {QUIZ.length}</span>
                      <span style={{ fontSize: 13, color: '#84cc16' }}>Score: {quiz.score}</span>
                    </div>
                    <div style={{ background: 'var(--bg-primary)', borderRadius: 8, marginBottom: 24, height: 6 }}>
                      <div style={{ height: '100%', background: '#84cc16', borderRadius: 8, width: (quiz.current / QUIZ.length * 100) + '%', transition: 'width 0.3s' }} />
                    </div>
                    <h3 style={{ fontSize: 18, fontWeight: 600, marginBottom: 24, lineHeight: 1.5 }}>{QUIZ[quiz.current].q}</h3>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 24 }}>
                      {QUIZ[quiz.current].options.map(function(opt, i) {
                        let bg = 'var(--bg-secondary)', border = 'var(--border)', color = 'var(--text-primary)'
                        if (quiz.answered) {
                          if (i === QUIZ[quiz.current].answer) { bg = '#10b98118'; border = '#10b981'; color = '#10b981' }
                          else if (i === quiz.selected && i !== QUIZ[quiz.current].answer) { bg = '#ef444418'; border = '#ef4444'; color = '#ef4444' }
                        }
                        return (
                          <div key={i} onClick={function() { handleAnswer(i) }} style={{ padding: '14px 20px', borderRadius: 10, cursor: quiz.answered ? 'default' : 'pointer', background: bg, border: '1px solid ' + border, color: color, fontSize: 14, fontWeight: 500, transition: 'all 0.2s' }}>
                            {['A', 'B', 'C', 'D'][i]}. {opt}
                          </div>
                        )
                      })}
                    </div>
                    {quiz.answered && (
                      <div>
                        <div style={{ background: '#10b98118', border: '1px solid #10b98144', borderRadius: 10, padding: 16, marginBottom: 16, fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
                          Explanation: {QUIZ[quiz.current].explanation}
                        </div>
                        <button onClick={nextQuestion} style={{ background: '#84cc16', color: '#000', border: 'none', padding: '12px 28px', borderRadius: 8, fontSize: 15, fontWeight: 600, cursor: 'pointer' }}>
                          {quiz.current + 1 >= QUIZ.length ? 'See Results' : 'Next Question →'}
                        </button>
                      </div>
                    )}
                  </div>
                )
                : (
                  <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 16, padding: 48, textAlign: 'center' }}>
                    <div style={{ fontSize: 64, marginBottom: 16 }}>{quiz.score === 6 ? '🏆' : quiz.score >= 4 ? '👍' : '📚'}</div>
                    <h3 style={{ fontSize: 28, fontWeight: 800, marginBottom: 8 }}>You scored {quiz.score} / {QUIZ.length}</h3>
                    <p style={{ color: 'var(--text-secondary)', marginBottom: 32 }}>
                      {quiz.score === 6 ? 'Perfect! You mastered Chapter 9!' : quiz.score >= 4 ? 'Good work! Review sections you missed.' : 'Keep studying — re-read the sections.'}
                    </p>
                    <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
                      <button onClick={function() { setQuiz({ current: 0, selected: null, answered: false, score: 0, done: false }) }} style={{ background: 'var(--bg-secondary)', color: 'var(--text-primary)', border: '1px solid var(--border)', padding: '12px 24px', borderRadius: 8, fontSize: 14, cursor: 'pointer', fontWeight: 600 }}>Retry Quiz</button>
                      <button onClick={function() { window.location.href = '/chapter/10' }} style={{ background: '#84cc16', color: '#000', border: 'none', padding: '12px 24px', borderRadius: 8, fontSize: 14, cursor: 'pointer', fontWeight: 600 }}>Next: Chapter 10 →</button>
                    </div>
                  </div>
                )}
            </div>
          )}

        </div>
      </div>
    </div>
  )
}